### ISSUE TITLE
Setting up a self-hosted runner (or runners) for benchmarking

### ISSUE THREAD

**Issue by vielmetti** [SecuringCarter/LanguageRepo#2]
@tylerbenson and @vielmetti have been working through some issues and constraints for running benchmarking runs through one or more self-hosted runners on Equinix Metal, part of the CNCF Community Infrastructure Lab hosted at Equinix.

Some constraints we're looking at (let me know if I have these right or wrong): 

1. Multiple projects will be doing benchmarking runs, and a job on one project should not interfere with another.
2. Individual benchmark runs will be time-bound (e.g. 30 or 60 minutes) and should not run for a "long time".
3. The runner configuration should be "secure", in the best sense of Github self-hosted runner configuration for a public repo; this must mean that it's resilient against loss of secrets and prevents crypto-mining (to name only two risks).
4. Not every check-in needs to be tested, but periodically a protected branch should be tested.

**Comment by tylerbenson** [comment]
1. they can be delayed by each other depending on runner availability, but should not run concurrently or break things.
2. yes.  Ideally this is configurable at the runner level to constrain this shared resource from being unintentionally abused.
3. yes.
4. yes, though some repos might have justification to run more frequently that's not currently the intent.
